version: '3.8'

services:
  dev:
    image: a1-sdk-builder-fixed:latest
    container_name: A1_Builder
    command: ["/bin/bash", "-lc", "sleep infinity"]
    restart: unless-stopped
    stdin_open: true    # -i
    tty: true           # -t
    volumes:
      # 挂载 SDK 数据
      - ../data:/app/smartsens_sdk
      # 挂载 src 目录
      - ../src:/app/src
      # 挂载模型目录
      - ../models:/app/models
      # 挂载输出目录
      - ../output:/app/output
    working_dir: /app/src
    ports:
      - "8080:8080"
    # 如有需要，指定 entrypoint
    # entrypoint: /app/src/docker/entrypoint.sh